# Generated by Django 4.2.14 on 2025-11-04 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rider_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
