# Generated by Django 4.2.14 on 2025-11-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_rider_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rider_id',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
